### ISSUE TITLE
Bluebird

### ISSUE THREAD

**Issue by Harut** [lostpebble/koa-mobx-react-starter#4]
Hi! Can you please reason this line? It is not obvious for server-side rendering newbies like me. A comment in the file would be great!

```js
require('babel-runtime/core-js/promise').default = require('bluebird');
```

https://github.com/lostpebble/koa-mobx-react-starter/blob/master/src/server/babel-server.js#L6

**Comment by lostpebble** [comment]
Sure thing, I've added some comments in the code in that file. Hope it helps!
