### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by gkbn** [lostpebble/koa-mobx-react-starter#5]
Hello @lostpebble! Thank you so much for the project; it looks like fitting well for what I have been looking for. 

Can you please add the license terms so that I (and other developers of course) can use the project as a starter for my web app without having to worry about any issues in future?

**Comment by lostpebble** [comment]
Hi @gkbn 

No problem. I've updated the project with a License file - basically an "Unlicense" file actually - which gives anyone pretty much open and unattributed use of this project. See the UNLICENSE.txt for more details.
